name: iOS CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Xcode
        uses: actions/setup-xcode@v2
        with:
          xcode-version: '13.2'
          xcpretty-version: '0.3.0'

      - name: Install CocoaPods
        run: |
          gem install cocoapods --no-document
          pod install

      - name: Build and Test
        run: |
          xcodebuild -workspace hello-world.xcworkspace -scheme hello-world -destination 'platform=iOS Simulator,name=iPhone 13' clean test | xcpretty
